before_install:
  - sdk install java 25.0.1.fx-librca
  - curl -JLOs https://raw.githubusercontent.com/sireum/kekinian/master/versions.properties
  - mkdir bin
  - curl -JLso bin/init.sh https://raw.githubusercontent.com/sireum/kekinian/master/bin/init.sh
  - curl -JLso bin/sireum https://raw.githubusercontent.com/sireum/kekinian/master/bin/sireum
  - cat versions.properties
  - chmod +x bin/init.sh bin/sireum
  - SIREUM_NO_SETUP=true bin/init.sh
install:
  - unset JAVA_TOOL_OPTIONS
  - SIREUM_PROVIDED_JAVA=true bin/sireum proyek publish --target jvm . org.sireum.forms
  - rm -fR lib/cache
