before_install:
  - set -x
  - rm -fR bin versions.properties
  - curl -JLO https://raw.githubusercontent.com/sireum/kekinian/master/versions.properties
  - mkdir bin
  - curl -JLo bin/init.sh https://raw.githubusercontent.com/sireum/kekinian/master/bin/init.sh
  - curl -JLo bin/sireum https://raw.githubusercontent.com/sireum/kekinian/master/bin/sireum
  - cat versions.properties
  - chmod +x bin/init.sh bin/sireum
  - SIREUM_NO_SETUP=true bin/init.sh
install:
  - set -x
  - unset JAVA_TOOL_OPTIONS
  - bin/sireum proyek publish --target jvm . org.sireum.forms
  - rm -fR lib/cache
