name: ci

on:
  push:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        run: |
          rm -fR "$GITHUB_WORKSPACE/Forms" "$GITHUB_WORKSPACE/Sireum"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Forms
      - name: Build
        run: |
          wget https://github.com/sireum/rolling/releases/download/m2/osthemedetector.tar.gz
          tar xf osthemedetector.tar.gz
          mkdir $HOME/.m2/repository/
          mv com $HOME/.m2/repository/
          export SIREUM_HOME="$GITHUB_WORKSPACE/Sireum"
          git clone --depth=1 https://github.com/sireum/kekinian Sireum
          Sireum/bin/init.sh
          Sireum/bin/sireum proyek assemble --main org.sireum.forms.FormsApp --exclude-jar-deps asm:,unmanaged:,org.scala-lang: Forms
